### ISSUE TITLE
Change build for web script to not use secret

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#367]
This is what we do in another Flutter application...

```
on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.3'
      - run: |
          flutter pub get
          flutter build web

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
```
